### ISSUE TITLE
Thunderbird 148 + (latest) beta version support for FiltaQuilla

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/FiltaQuilla#262]
Latest version, installs in 126.0b1 below:

[filtaquilla-4.1pre8.zip](https://github.com/RealRaven2000/FiltaQuilla/files/15119083/filtaquilla-4.1pre8.zip)

-------

To install version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Latest version, installs in 127.0b1 below:

[filtaquilla-4.1pre25.zip](https://github.com/RealRaven2000/FiltaQuilla/files/15362794/filtaquilla-4.1pre25.zip)

----

To install version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Latest test version, compatible with beta 128 - which is close to the final release of Thunderbird ESR 128.0 planned for this summer.]

[filtaquilla-4.1pre26.zip](https://github.com/user-attachments/files/15836828/filtaquilla-4.1pre26.zip)

-----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Latest test version, compatible with - compatible with Tb 128.*, tested on current beta 128.0b3. This also fixes issue #265.

[filtaquilla-4.1pre27.zip](https://github.com/user-attachments/files/15968986/filtaquilla-4.1pre27.zip)

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Implemented in 4.1 - Published 16/07/2024

**Comment by RealRaven2000** [comment]
Reopening the issue until ATN is done reviewing the version.

**Comment by RealRaven2000** [comment]
Latest version, bumped to Tb 130.*

[filtaquilla-4.2pre7.zip](https://github.com/user-attachments/files/16829816/filtaquilla-4.2pre7.zip)

Contains changes for issue #269,  #270

----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Latest version, bumped to Tb 131.*

[filtaquilla-4.2pre8.zip](https://github.com/user-attachments/files/16930149/filtaquilla-4.2pre8.zip)

----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by johndoe1969** [comment]
I just upgraded to Thunderbird 128.2.2esr (64-bit). I'm running Arch and have the latest updates.

I let filtaQuilla update itself to v4.1. I noticed when I manually run my filters (for RSS feeds), that Thunderbird would freeze and eventually give me an option to restart the program if I hadn't already forced it to shutdown.

I came across this post and tried filtaquilla 4.2pre8. The issue seems to have gone away. It does seem however that it takes a few secs longer to run through my filters when I do a manual run. No biggie to me, just an fyi.

Update 09/27/2024: Thunderbird is not completely freezing and then crashing with 4.2pre8, but does lock-up for about 2-3 mins when I manually run my filters. The more the RSS feeds to filter through the longer the lock-up. Now using Thunderbird 128.2.3esr.

**Comment by RealRaven2000** [comment]
Latest version, bumped to Tb 132.*

[filtaquilla-4.2pre9.zip](https://github.com/user-attachments/files/17266139/filtaquilla-4.2pre9.zip)

----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Latest version, bumped to Tb 133.*

[filtaquilla-4.3pre66.zip](https://github.com/user-attachments/files/17792172/filtaquilla-4.3pre66.zip)

----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Test version for Thunderbird 136.*:

[filtaquilla-4.3.2pre24.zip](https://github.com/user-attachments/files/18847851/filtaquilla-4.3.2pre24.zip)

also deals with issue #331 among other things

----

To try out this version, download the zip file and then drag it into Thunderbird Add-ons Manager (without extracting). You also HAVE TO restart, as there are new ESM modules (these are usually aggressively cached by Thunderbird)

**Comment by RealRaven2000** [comment]
Test version for Thunderbird 136.*:

As `saveAttachmentToFile()` was removed from Thunderbird in the latest releases, here is a quick workaround, using an API method to retrieve the attachments  and then saving the files in an experimental API:

[filtaquilla-4.4pre36.zip](https://github.com/user-attachments/files/19495409/filtaquilla-4.4pre36.zip)

---

To try out this version, download the zip file and then drag it into Thunderbird Add-ons Manager (without extracting). You also HAVE TO restart, as custom filter actions cannot be removed from the service. Only way to update them is a restart.

**Comment by RealRaven2000** [comment]
The particular helper function `saveAllAttachments()` was removed in c-c. So I implemented saving attachments in a different way. 

Tb 128:
https://searchfox.org/comm-esr128/source/mailnews/base/public/nsIMessenger.idl#72

- this function is removed in comm-central.

The other function `detachAttachmentsWOPrompts()`, which is used for detaching them, still exists in the modern code (comm-central):
Tb136:
https://searchfox.org/comm-central/source/mailnews/base/public/nsIMessenger.idl#85

so I created a new branch ESR128 as default, and ESR115 won't get any new versions, all new releases are v5.*, minimum Thunderbird 128

**Comment by RealRaven2000** [comment]
Added renaming rules to the new save attachments function. Also minimum version = 128!

[filtaquilla-5.0pre43.zip](https://github.com/user-attachments/files/19513427/filtaquilla-5.0pre43.zip)

----

To try out this version, download the zip file and then drag it into Thunderbird Add-ons Manager (without extracting). You also **HAVE TO** restart, as custom filter actions cannot be removed from the service. Only way to update them is a restart.

**Comment by RealRaven2000** [comment]
Latest Beta support. Tested in Thunderbird 137.0b2

[filtaquilla-5.0pre83.zip](https://github.com/user-attachments/files/19608508/filtaquilla-5.0pre83.zip)

---

To try out this version, download the zip file and then drag it into Thunderbird Add-ons Manager (without extracting). You also HAVE TO restart, as custom filter actions cannot be removed from the service. Only way to update them is a restart.

**Comment by RealRaven2000** [comment]
Latest beta support (141.*)

[filtaquilla-5.3pre2.zip](https://github.com/user-attachments/files/20963794/filtaquilla-5.3pre2.zip)

---

To install version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Beta support (141.0b1)

[filtaquilla-5.3.1pre3.zip](https://github.com/user-attachments/files/20997344/filtaquilla-5.3.1pre3.zip)

contains minor fixes related to Thunderbird removing `nsIMsgFolder.prettyName`.

---

To install version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Beta support (143.0b2)

[filtaquilla-5.3.2pre4.zip](https://github.com/user-attachments/files/22051271/filtaquilla-5.3.2pre4.zip)

----

To install version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Latest version, bumped to 149.*

[filtaquilla-6.1pre5.zip](https://github.com/user-attachments/files/24614882/filtaquilla-6.1pre5.zip)

----

To install version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by knoxg** [comment]
Hi there. 

I recently upgraded thunderbird to 149.0.1 ( 202603252102025 ), and it appears to have broken the filtaquilla extension ? 

Tried disabling and then re-enabling, and then reinstalling from the the thunderbird.net site ( https://addons.thunderbird.net/en-US/thunderbird/addon/filtaquilla/?src=search ).  Also tried the filtaquilla-6.1pre5.zip above.

Every attempt displays this message up the top-right of the main window for me:

<img width="440" height="188" alt="Image" src="https://github.com/user-attachments/assets/31008cbd-1ab2-43d9-adf4-e76db3f5fc54" />

I tried installing the plugin with the error console open, saw this appear in the console:

```
1775453260825	addons.xpi	WARN	Invalid XPI: TypeError: context.postprocessors[this.postprocessor] is not a function(resource://gre/modules/Schemas.sys.mjs:1463:59) JS Stack trace: postprocess@Schemas.sys.mjs:1463:59
normalize@Schemas.sys.mjs:2461:17
checkProperty/r<@Schemas.sys.mjs:2224:16
withPath@Schemas.sys.mjs:756:14
checkProperty@Schemas.sys.mjs:2223:25
normalize@Schemas.sys.mjs:2296:14
normalize@Schemas.sys.mjs:3908:23
normalize@Schemas.sys.mjs:4122:28
_getNormalizedManifest@Extension.sys.mjs:1700:25
parseManifest@Extension.sys.mjs:1827:33
```

**Comment by RealRaven2000** [comment]
weird, it works for me here - Filtaquilla 6.1 in current release 149.0.1.

<img width="990" height="552" alt="Image" src="https://github.com/user-attachments/assets/ede16eac-9690-4d03-a0aa-725db9391d97" />

It is marked as compatible up to v151. Can you download the latest version [from here](https://addons.thunderbird.net/en-US/thunderbird/addon/filtaquilla/) and then drag the xpi into Add-ons Manager?

**Comment by knoxg** [comment]
Interesting, checked my thunderbird version again under Help -> About, and it said that a new update was available

Installed the thunderbird update which took me up to 149.0.2, and then tried installing the xpi again ( latest xpi from that link was the same xpi I had tried earlier ) and it works !

Thanks for the help, keep up the good work :)

**Comment by RealRaven2000** [comment]
Latest version

[filtaquilla-6.2pre33.zip](https://github.com/user-attachments/files/29045122/filtaquilla-6.2pre33.zip)

includes changes for #398 (WIP).

When updating from Tb152 to 153 - I highly recommend switching to 153ESR, as Thunderbird wants to discontinue legacy Add-on support on the release train from next year.

-----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)
